import { Inter } from "next/font/google";
import "../globals.css";
import { Toaster } from "@/components/ui/toaster";
import Header from "../../components/layout/webapp/header";
import Sidebar from "@/components/layout/webapp/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="h-16 sticky top-0 border-b border-gray-600 ">
          <Header />
        </header>
        <main className="min-h-[calc(100vh-4rem)] flex w-full ">
          <Sidebar />
          <div className="flex-grow w-[calc(100vw-16rem)] p-3">

            {children}
          </div>
        </main>
        <Toaster />
      </body>
    </html>
  );
}
